spring.application.name=BookingSystem


spring.datasource.url=jdbc:postgresql://localhost:5432/Booking
spring.datasource.username=postgres
spring.datasource.password=456784
spring.jpa.hibernate.ddl-auto=update
