spring.application.name=BookingSystem


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

app.jwtSecret=${APP_JWT_SECRET}
app.jwtExpirationMs=${APP_JWT_EXPIRATION_MS}

